cc_binary(
    name = "libpjrt_plugin_mpi.so",
    srcs = [
        "src/pjrt_plugin/mpi_buffer.cc",
        "src/pjrt_plugin/mpi_buffer.h",
        "src/pjrt_plugin/mpi_client.h",
        "src/pjrt_plugin/mpi_executable.cc",
        "src/pjrt_plugin/mpi_executable.h",
        "src/pjrt_plugin/pjrt_api.cc",
        "src/pjrt_plugin/pjrt_client.cc",
        "src/pjrt_plugin/pjrt_client.h",
        "src/pjrt_plugin/pjrt_device.cc",
        "src/pjrt_plugin/pjrt_device.h",
        "src/pjrt_plugin/pjrt_error.cc",
        "src/pjrt_plugin/pjrt_error.h",
        "src/pjrt_plugin/pjrt_memory.cc",
        "src/pjrt_plugin/pjrt_memory.h",
        "src/pjrt_plugin/pjrt_mutex.h",
        "src/pjrt_plugin/pjrt_plugin.h",
        "src/pjrt_plugin/pjrt_topology.cc",
        "src/pjrt_plugin/pjrt_topology.h",
        "src/pjrt_plugin/pjrt_types.cc",
        "src/pjrt_plugin/pjrt_types.h",
    ],
    includes = ["src"],
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "@mpi",
        "@xla//xla:shape_util",
        "@xla//xla/client:client_library",
        "@xla//xla/client:executable_build_options",
        "@xla//xla/client:local_client",
        "@xla//xla/hlo/builder:xla_computation",
        "@xla//xla/mlir/utils:type_util",
        "@xla//xla/pjrt/c:pjrt_c_api_hdrs",
        "@xla//xla/pjrt/c:pjrt_c_api_helpers",
        "@xla//xla/pjrt:mlir_to_hlo",
        "@xla//xla/service:computation_placer",
        "@xla//xla/service:executable",
        "@xla//xla/service:maybe_owning_device_address",
        "@xla//xla/service:shaped_buffer",
        "@xla//xla/service/cpu:cpu_transfer_manager",
        "@xla//xla/service/cpu:cpu_compiler",
        "@xla//xla/backends/cpu:alignment",
        "@tsl//tsl/platform:platform_port",
        "@xla//xla/stream_executor:device_address",
        "@xla//xla/stream_executor/host:host_platform",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
        "@llvm-project//mlir:FuncDialect",
        "@llvm-project//mlir:IR",
    ],
)
