cc_binary(
    name = "libpjrt_plugin_mpi.so",
    srcs = [
        "src/pjrt_plugin/mpi_buffer.cc",
        "src/pjrt_plugin/mpi_buffer.h",
        "src/pjrt_plugin/mpi_client.h",
        "src/pjrt_plugin/mpi_executable.cc",
        "src/pjrt_plugin/mpi_executable.h",
        "src/pjrt_plugin/pjrt_api.cc",
        "src/pjrt_plugin/pjrt_client.cc",
        "src/pjrt_plugin/pjrt_client.h",
        "src/pjrt_plugin/pjrt_device.cc",
        "src/pjrt_plugin/pjrt_device.h",
        "src/pjrt_plugin/pjrt_error.cc",
        "src/pjrt_plugin/pjrt_error.h",
        "src/pjrt_plugin/pjrt_memory.cc",
        "src/pjrt_plugin/pjrt_memory.h",
        "src/pjrt_plugin/pjrt_mutex.h",
        "src/pjrt_plugin/pjrt_plugin.h",
        "src/pjrt_plugin/pjrt_topology.cc",
        "src/pjrt_plugin/pjrt_topology.h",
        "src/pjrt_plugin/pjrt_types.cc",
        "src/pjrt_plugin/pjrt_types.h",
    ],
    includes = ["src"],
    linkshared = 1,
    linkstatic = 1,
    deps = [
        "@mpi",
        "@xla//xla:shape_util",
        "@xla//xla/pjrt/c:pjrt_c_api_hdrs",
        "@xla//xla/pjrt/c:pjrt_c_api_helpers",
        "@xla//xla/service:computation_placer",
    ],
)
